baseURL: https://sylviamoss.github.io
languageCode: en-us
defaultContentLanguage: en
title: Sylvia Moss
theme: cupper-hugo-theme
disqusShortname: sylviamoss
enableGitInfo: true
googleAnalytics: G-Y4T9TYJ5VX

taxonomies:
  tag: tags

permalinks:
  post: /post/:filename/
  german: /german/:filename/
  playlist: /:filename/

imaging:
  quality: 99

params:
  # description: My software engineering things and hobbies.
  navTitleText: Halli Hallo
  logoAlt: An alternative text description of the logo
  homeMetaContent: Just dev related thing I did and think about. Some musics I listen while coding, and german content.
  footer: Made with [Hugo](https://gohugo.io/). Themed by [Cupper](https://github.com/zwbetz-gh/cupper-hugo-theme).
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat: Mon, 02 Jan 2006
  katex: true
  search: true
  showThemeSwitcher: false
  darkThemeAsDefault: false
  customCss:
    - css/home.css # relative path starting from static/

menu:
  nav:
    - name: Home
      url: /
      weight: 1
    # - name: Resume
    #   url: /resume/
    #   weight: 2
    - name: Blog
      url: /post/
      weight: 2
    - name: German
      url: /german/
      weight: 3
    - name: Playlist
      url: /playlist/
      weight: 4
    - name: Tags
      url: /tags/
      weight: 5

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
