baseURL: https://sylviamoss.github.io
languageCode: en-us
defaultContentLanguage: en
title: Sylvia Moss
theme: cupper-hugo-theme
disqusShortname: moss
enableGitInfo: true

taxonomies:
  tag: tags

permalinks:
  post: /:filename/
  playlist: /:filename/

imaging:
  quality: 99

params:
  description: My dev things and some music I listen while coding.
  homeMetaContent: Just dev related thing I did and think about. Some musics I listen while coding as well.
  footer: Made with [Hugo](https://gohugo.io/). Themed by [Cupper](https://github.com/zwbetz-gh/cupper-hugo-theme).
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat: Mon, 02 Jan 2006
  katex: true
  darkThemeAsDefault: false

menu:
  nav:
    - name: Home
      url: /
      weight: 1
    - name: Blog
      url: /post/
      weight: 2
    - name: Playlist
      url: /playlist/
      weight: 3
    - name: Tags
      url: /tags/
      weight: 4

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
